# Generated by Django 6.0.7 on 2026-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de pessoa')),
                ('classificacao', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('AMBOS', 'Cliente e Fornecedor')], default='CLIENTE', max_length=15, verbose_name='Classificação')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CPF / CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['razao_social'],
            },
        ),
    ]
