# Generated by Django 6.0.7 on 2026-08-19 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0011_alter_lancamentofinanceiroclassificacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_acesso_recebidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_acesso_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acessos_empresariais_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_autorizados', to='financeiro.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username', 'empresa__razao_social'],
                'permissions': [('view_configuracoes', 'Pode acessar a Central de Configurações'), ('gerenciar_acessos', 'Pode gerenciar usuários, perfis e empresas autorizadas')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='uq_usuario_empresa')],
            },
        ),
    ]
