# Generated by Django 6.0.7 on 2026-08-19 18:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0011_alter_lancamentofinanceiroclassificacao_options_and_more'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=30)),
                ('nome_apresentacao', models.CharField(blank=True, max_length=200)),
                ('cargo_atual', models.CharField(max_length=120)),
                ('data_admissao', models.DateField()),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('FERIAS', 'Férias'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=15)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('conta', models.CharField(blank=True, max_length=30)),
                ('chave_pix', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='financeiro.empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_funcionais', to='pessoas.pessoa')),
            ],
            options={
                'ordering': ['pessoa__razao_social'],
                'permissions': [('view_rh', 'Pode acessar o RH'), ('view_remuneracao', 'Pode visualizar remuneração'), ('change_remuneracao', 'Pode alterar remuneração'), ('ajustar_ponto', 'Pode lançar e ajustar ponto'), ('fechar_ponto', 'Pode fechar competência de ponto'), ('reabrir_ponto', 'Pode reabrir competência de ponto'), ('lancar_evento_folha', 'Pode lançar eventos de folha'), ('fechar_folha_gerencial', 'Pode fechar folha gerencial'), ('registrar_retorno_contabilidade', 'Pode registrar retorno da contabilidade'), ('conferir_folha', 'Pode conferir folha'), ('view_dados_bancarios', 'Pode visualizar dados bancários de funcionário')],
            },
        ),
        migrations.CreateModel(
            name='EventoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ADIANTAMENTO', 'Adiantamento'), ('FALTA', 'Falta'), ('ATESTADO', 'Atestado'), ('BENEFICIO', 'Beneficio'), ('PREMIO', 'Premio'), ('ABONO', 'Abono'), ('ADICIONAL_NOTURNO', 'Adicional Noturno'), ('HORA_100', 'Hora 100'), ('DESCONTO_BH', 'Desconto Bh'), ('VALE_TRANSPORTE', 'Vale Transporte'), ('OUTROS', 'Outros')], max_length=30)),
                ('descricao', models.CharField(max_length=200)),
                ('natureza', models.CharField(choices=[('PROVENTO', 'Provento'), ('DESCONTO', 'Desconto'), ('INFORMATIVO', 'Informativo')], max_length=12)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unidade', models.CharField(choices=[('VALOR', 'Valor'), ('HORAS', 'Horas'), ('DIAS', 'Dias'), ('OUTRO', 'Outro')], default='VALOR', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('origem', models.CharField(default='MANUAL', max_length=30)),
                ('chave_origem', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFERIDO', 'Conferido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_folha', to='financeiro.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_folha', to='rh.funcionario')),
            ],
            options={
                'ordering': ['-competencia', 'funcionario', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ContratoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('divisor_salarial', models.PositiveIntegerField(default=220)),
                ('carga_semanal_minutos', models.PositiveIntegerField(default=2640)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='rh.funcionario')),
            ],
            options={
                'ordering': ['-inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='CompetenciaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Primeiro dia do mês')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APURADO', 'Apurado'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto')], default='RASCUNHO', max_length=12)),
                ('saldo_anterior_minutos', models.IntegerField(default=0)),
                ('creditos_minutos', models.PositiveIntegerField(default=0)),
                ('debitos_minutos', models.PositiveIntegerField(default=0)),
                ('ajustes_minutos', models.IntegerField(default=0)),
                ('saldo_final_minutos', models.IntegerField(default=0)),
                ('horas_100_minutos', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias_rh_fechadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias_ponto', to='rh.funcionario')),
            ],
            options={
                'ordering': ['-competencia', 'funcionario'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_rh', to='financeiro.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='rh.funcionario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Jornada padrão', max_length=100)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='rh.funcionario')),
            ],
            options={
                'ordering': ['-inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='JornadaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('trabalha', models.BooleanField(default=True)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('saida_intervalo', models.TimeField(blank=True, null=True)),
                ('retorno_intervalo', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('minutos_previstos', models.PositiveIntegerField(default=0)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='rh.jornada')),
            ],
            options={
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='MarcacaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('origem', models.CharField(choices=[('RELOGIO', 'Relógio'), ('MANUAL', 'Manual'), ('IMPORTADO', 'Importado'), ('PRE_ASSINALADO', 'Pré-assinalado')], max_length=15)),
                ('observacao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='rh.funcionario')),
                ('substitui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes', to='rh.marcacaoponto')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'horario', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('FALTA', 'Falta'), ('ATESTADO', 'Atestado'), ('AFASTAMENTO', 'Afastamento'), ('ABONO', 'Abono'), ('ATRASO_JUSTIFICADO', 'Atraso justificado'), ('AJUSTE_PONTO', 'Ajuste de ponto'), ('OUTRO', 'Outro')], max_length=22)),
                ('descricao', models.CharField(max_length=200)),
                ('observacao', models.TextField(blank=True)),
                ('minutos_abonados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_ponto', to='rh.funcionario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetornoContabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('salario_holerite', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('inss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('irrf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('beneficios', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('horas_extras', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('adicional_noturno', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('faltas_descontos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('premio_abono', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('outros', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('liquido_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retornos_contabilidade', to='rh.funcionario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenciaFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFERIDO', 'Conferido'), ('DIVERGENTE', 'Divergente'), ('JUSTIFICADO', 'Justificado')], default='PENDENTE', max_length=12)),
                ('justificativa', models.TextField(blank=True)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('retorno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conferencia', to='rh.retornocontabilidade')),
            ],
        ),
        migrations.CreateModel(
            name='ValeAdiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantidade_parcelas', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('QUITADO', 'Quitado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales', to='rh.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ValeParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('competencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DESCONTADA', 'Descontada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='rh.valeadiantamento')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ApuracaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('minutos_previstos', models.PositiveIntegerField(default=0)),
                ('minutos_trabalhados', models.PositiveIntegerField(default=0)),
                ('credito_bh_minutos', models.PositiveIntegerField(default=0)),
                ('debito_bh_minutos', models.PositiveIntegerField(default=0)),
                ('horas_100_minutos', models.PositiveIntegerField(default=0)),
                ('adicional_noturno_minutos', models.PositiveIntegerField(default=0)),
                ('falta', models.BooleanField(default=False)),
                ('abonado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuracoes', to='rh.competenciaponto')),
            ],
            options={
                'ordering': ['data'],
                'constraints': [models.UniqueConstraint(fields=('competencia', 'data'), name='uq_apuracao_competencia_data')],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=150)),
                ('localidade', models.CharField(blank=True, max_length=120)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados_rh', to='financeiro.empresa')),
            ],
            options={
                'ordering': ['data'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'data'), name='uq_feriado_empresa_data')],
            },
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.UniqueConstraint(fields=('empresa', 'pessoa'), name='uq_funcionario_empresa_pessoa'),
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.UniqueConstraint(condition=models.Q(('matricula', ''), _negated=True), fields=('empresa', 'matricula'), name='uq_funcionario_empresa_matricula'),
        ),
        migrations.AddConstraint(
            model_name='eventofolha',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_origem', ''), _negated=True), fields=('empresa', 'chave_origem'), name='uq_evento_empresa_chave_origem'),
        ),
        migrations.AddConstraint(
            model_name='competenciaponto',
            constraint=models.UniqueConstraint(fields=('funcionario', 'competencia'), name='uq_competencia_funcionario_mes'),
        ),
        migrations.AddConstraint(
            model_name='jornadadia',
            constraint=models.UniqueConstraint(fields=('jornada', 'dia_semana'), name='uq_jornada_dia'),
        ),
        migrations.AddConstraint(
            model_name='retornocontabilidade',
            constraint=models.UniqueConstraint(fields=('funcionario', 'competencia'), name='uq_retorno_funcionario_competencia'),
        ),
        migrations.AddConstraint(
            model_name='valeparcela',
            constraint=models.UniqueConstraint(fields=('vale', 'numero'), name='uq_vale_numero_parcela'),
        ),
    ]
