# Generated by Django 6.0.7 on 2026-08-19 02:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0009_obras_centros_custo'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloConteudoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False)),
                ('texto_introdutorio', models.TextField(blank=True)),
                ('normas_procedimentos', models.TextField(blank=True)),
                ('qualificacao_mao_obra', models.TextField(blank=True)),
                ('obrigacoes_contratada', models.TextField(blank=True)),
                ('observacoes_comerciais', models.TextField(blank=True)),
                ('observacao_faturamento', models.TextField(blank=True)),
                ('texto_impostos', models.TextField(blank=True)),
                ('multa_juros_atraso', models.TextField(blank=True)),
                ('regra_protesto', models.TextField(blank=True)),
                ('rodape', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_proposta', to='financeiro.empresa')),
            ],
            options={
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('numero_sequencial', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em revisão'), ('ENVIADA', 'Enviada'), ('EM_NEGOCIACAO', 'Em negociação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('revisao_atual', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposta_origem', to='financeiro.centrocusto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas_cliente', to='pessoas.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='financeiro.empresa')),
                ('responsavel_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PropostaHistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em revisão'), ('ENVIADA', 'Enviada'), ('EM_NEGOCIACAO', 'Em negociação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='comercial.proposta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PropostaRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=0)),
                ('data_proposta', models.DateField()),
                ('nome_servico', models.CharField(max_length=250)),
                ('aos_cuidados_de', models.CharField(blank=True, max_length=150)),
                ('escopo_incluido', models.TextField(blank=True)),
                ('nao_incluso', models.TextField(blank=True)),
                ('prazo_entrega', models.CharField(blank=True, max_length=200)),
                ('tipo_frete', models.CharField(blank=True, max_length=100)),
                ('condicao_pagamento', models.TextField(blank=True)),
                ('validade_dias', models.PositiveIntegerField(default=15)),
                ('valida_ate', models.DateField(blank=True, null=True)),
                ('texto_introdutorio', models.TextField(blank=True)),
                ('exibir_texto_introdutorio', models.BooleanField(default=True)),
                ('normas_procedimentos', models.TextField(blank=True)),
                ('exibir_normas_procedimentos', models.BooleanField(default=True)),
                ('qualificacao_mao_obra', models.TextField(blank=True)),
                ('exibir_qualificacao_mao_obra', models.BooleanField(default=True)),
                ('obrigacoes_contratada', models.TextField(blank=True)),
                ('exibir_obrigacoes_contratada', models.BooleanField(default=True)),
                ('observacoes_comerciais', models.TextField(blank=True)),
                ('exibir_observacoes_comerciais', models.BooleanField(default=True)),
                ('observacao_faturamento', models.TextField(blank=True)),
                ('texto_impostos', models.TextField(blank=True)),
                ('multa_juros_atraso', models.TextField(blank=True)),
                ('regra_protesto', models.TextField(blank=True)),
                ('dados_bancarios', models.TextField(blank=True)),
                ('responsavel_nome', models.CharField(blank=True, max_length=150)),
                ('responsavel_cargo', models.CharField(blank=True, max_length=100)),
                ('assinatura_textual', models.CharField(blank=True, max_length=200)),
                ('rodape', models.TextField(blank=True)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('formacao_preco', models.CharField(choices=[('MARKUP', 'Markup'), ('MARGEM', 'Margem'), ('MANUAL', 'Preço manual')], default='MARKUP', max_length=10)),
                ('percentual_formacao', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('preco_venda_final', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('congelada', models.BooleanField(default=False)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa_nome_snapshot', models.CharField(blank=True, max_length=200)),
                ('empresa_documento_snapshot', models.CharField(blank=True, max_length=30)),
                ('cliente_nome_snapshot', models.CharField(blank=True, max_length=200)),
                ('cliente_documento_snapshot', models.CharField(blank=True, max_length=30)),
                ('conta_bancaria_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('modelo_conteudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.modeloconteudoproposta')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='comercial.proposta')),
            ],
            options={
                'ordering': ['proposta', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='PropostaLinhaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('grupo', models.CharField(choices=[('MATERIAL', 'Materiais'), ('SERVICO', 'Serviços')], max_length=10)),
                ('descricao', models.CharField(max_length=250)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacao', models.CharField(blank=True, max_length=250)),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_publicas', to='comercial.propostarevisao')),
            ],
            options={
                'ordering': ['grupo', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropostaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('MAO_OBRA', 'Mão de obra'), ('SERVICO_TERCEIRO', 'Serviço de terceiro'), ('FRETE', 'Frete'), ('LOCACAO_EQUIPAMENTO', 'Locação/equipamento'), ('OUTROS', 'Outros')], max_length=25)),
                ('descricao', models.CharField(max_length=250)),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=15)),
                ('unidade', models.CharField(default='UN', max_length=20)),
                ('custo_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('custo_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_proposta_fornecidos', to='pessoas.pessoa')),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_proposta', to='financeiro.planoconta')),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.propostarevisao')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropostaTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('percentual', models.DecimalField(decimal_places=4, max_digits=7)),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos', to='comercial.propostarevisao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='modeloconteudoproposta',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_modelo_proposta_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='proposta',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_proposta_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='proposta',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_sequencial'), name='uq_proposta_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='propostarevisao',
            constraint=models.UniqueConstraint(fields=('proposta', 'numero'), name='uq_proposta_revisao_numero'),
        ),
    ]
