# Generated by Django 6.0.7 on 2026-08-19 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-criado_em'], 'permissions': [('aprovar_proposta', 'Pode aprovar proposta'), ('rejeitar_proposta', 'Pode rejeitar proposta'), ('cancelar_proposta', 'Pode cancelar proposta'), ('criar_obra_proposta', 'Pode criar obra ao aprovar proposta')]},
        ),
        migrations.AddField(
            model_name='proposta',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposta',
            name='revisao_aprovada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_aprovadas', to='comercial.propostarevisao'),
        ),
    ]
