# Generated by Django 6.0.7 on 2026-08-19 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_proposta_options_proposta_aprovada_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='acompanhamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='proxima_acao',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='HistoricoContatoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('proxima_acao', models.CharField(blank=True, max_length=250)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_contatos', to='comercial.proposta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ocorrido_em'],
            },
        ),
    ]
