# Generated by Django 6.0.7 on 2026-08-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_proposta_acompanhamento_proposta_data_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='observacao_importacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Sistema'), ('IMPORTADO_HISTORICO', 'Importado histórico')], default='SISTEMA', max_length=25),
        ),
        migrations.AddField(
            model_name='proposta',
            name='status_historico',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
