# Generated by Django 6.0.7 on 2026-08-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGAR', 'Conta a pagar'), ('RECEBER', 'Conta a receber')], max_length=10, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('FISCAL', 'Documento fiscal'), ('COMERCIAL', 'Comercial'), ('CONCILIACAO', 'Conciliação bancária')], default='MANUAL', max_length=15, verbose_name='Origem')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Número do documento')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('data_competencia', models.DateField(blank=True, null=True, verbose_name='Data de competência')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor total')),
                ('status', models.CharField(choices=[('ABERTO', 'Em aberto'), ('PARCIAL', 'Parcialmente liquidado'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='financeiro.empresa', verbose_name='Empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='pessoas.pessoa', verbose_name='Cliente / Fornecedor')),
                ('plano_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.planoconta', verbose_name='Plano de contas')),
            ],
            options={
                'verbose_name': 'Lançamento financeiro',
                'verbose_name_plural': 'Lançamentos financeiros',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da parcela')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('status', models.CharField(choices=[('ABERTA', 'Em aberto'), ('PARCIAL', 'Parcialmente liquidada'), ('LIQUIDADA', 'Liquidada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.lancamentofinanceiro', verbose_name='Lançamento')),
            ],
            options={
                'verbose_name': 'Parcela financeira',
                'verbose_name_plural': 'Parcelas financeiras',
                'ordering': ['vencimento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='BaixaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da baixa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_financeiras', to='financeiro.contabancaria', verbose_name='Conta bancária')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.parcelafinanceira', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Baixa financeira',
                'verbose_name_plural': 'Baixas financeiras',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RateioCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_financeiros', to='financeiro.centrocusto', verbose_name='Centro de custo')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios_centro_custo', to='financeiro.lancamentofinanceiro', verbose_name='Lançamento')),
            ],
            options={
                'verbose_name': 'Rateio por centro de custo',
                'verbose_name_plural': 'Rateios por centro de custo',
                'ordering': ['centro_custo'],
            },
        ),
        migrations.AddConstraint(
            model_name='parcelafinanceira',
            constraint=models.UniqueConstraint(fields=('lancamento', 'numero'), name='unique_parcela_por_lancamento'),
        ),
        migrations.AddConstraint(
            model_name='rateiocentrocusto',
            constraint=models.UniqueConstraint(fields=('lancamento', 'centro_custo'), name='unique_centro_custo_por_lancamento'),
        ),
    ]
