# Generated by Django 6.0.7 on 2026-08-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_lancamentofinanceiro_parcelafinanceira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoOFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial do extrato')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data final do extrato')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=20, verbose_name='Status')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_ofx', to='financeiro.contabancaria', verbose_name='Conta bancária')),
            ],
            options={
                'verbose_name': 'Importação OFX',
                'verbose_name_plural': 'Importações OFX',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoOFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255, verbose_name='Identificador da transação')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('documento', models.CharField(blank=True, max_length=100, verbose_name='Documento / referência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCILIADO', 'Conciliado'), ('IGNORADO', 'Ignorado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('baixa_conciliada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_ofx_conciliados', to='financeiro.baixafinanceira', verbose_name='Baixa conciliada')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_ofx', to='financeiro.contabancaria', verbose_name='Conta bancária')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financeiro.importacaoofx', verbose_name='Importação')),
            ],
            options={
                'verbose_name': 'Movimento OFX',
                'verbose_name_plural': 'Movimentos OFX',
                'ordering': ['-data', '-id'],
                'constraints': [models.UniqueConstraint(fields=('conta_bancaria', 'identificador'), name='unique_movimento_ofx_por_conta')],
            },
        ),
    ]
