# Generated by Django 6.0.7 on 2026-08-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_importacaoofx_movimentoofx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da transferência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('documento', models.CharField(blank=True, max_length=100, verbose_name='Documento / referência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('EFETIVADA', 'Efetivada'), ('CANCELADA', 'Cancelada')], default='EFETIVADA', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='financeiro.contabancaria', verbose_name='Conta de destino')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='financeiro.contabancaria', verbose_name='Conta de origem')),
            ],
            options={
                'verbose_name': 'Transferência bancária',
                'verbose_name_plural': 'Transferências bancárias',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimentoofx',
            name='transferencia_conciliada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_ofx_conciliados', to='financeiro.transferenciabancaria', verbose_name='Transferência conciliada'),
        ),
    ]
