# Generated by Django 6.0.7 on 2026-08-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_transferenciabancaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('PAGAMENTO', 'Pagamento'), ('RECEBIMENTO', 'Recebimento'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste')], max_length=20, verbose_name='Origem')),
                ('descricao', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('documento', models.CharField(blank=True, max_length=100, verbose_name='Documento / referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('baixa_financeira', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_bancaria', to='financeiro.baixafinanceira', verbose_name='Baixa financeira')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_bancarias', to='financeiro.contabancaria', verbose_name='Conta bancária')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_bancarias', to='financeiro.transferenciabancaria', verbose_name='Transferência bancária')),
            ],
            options={
                'verbose_name': 'Movimentação bancária',
                'verbose_name_plural': 'Movimentações bancárias',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['conta_bancaria', 'data'], name='mov_banc_conta_data_idx')],
                'constraints': [models.UniqueConstraint(fields=('transferencia', 'conta_bancaria'), name='unique_movimentacao_transferencia_conta')],
            },
        ),
    ]
