# Generated by Django 6.0.7 on 2026-08-19 15:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def preencher_classificacoes_unicas(apps, schema_editor):
    Lancamento = apps.get_model('financeiro', 'LancamentoFinanceiro')
    Classificacao = apps.get_model('financeiro', 'LancamentoFinanceiroClassificacao')
    alias = schema_editor.connection.alias
    lote = []
    for lancamento in Lancamento.objects.using(alias).all().iterator(chunk_size=1000):
        lote.append(Classificacao(
            lancamento_id=lancamento.pk,
            plano_conta_id=lancamento.plano_conta_id,
            valor=lancamento.valor_total,
            ordem=1,
        ))
        if len(lote) >= 1000:
            Classificacao.objects.using(alias).bulk_create(lote, ignore_conflicts=True)
            lote = []
    if lote:
        Classificacao.objects.using(alias).bulk_create(lote, ignore_conflicts=True)

    total_lancamentos = Lancamento.objects.using(alias).count()
    validos = (
        Lancamento.objects.using(alias)
        .annotate(
            quantidade=models.Count('classificacoes_contabeis'),
            quantidade_valida=models.Count(
                'classificacoes_contabeis',
                filter=models.Q(
                    classificacoes_contabeis__plano_conta_id=models.F('plano_conta_id'),
                    classificacoes_contabeis__valor=models.F('valor_total'),
                ),
            ),
        )
        .filter(quantidade=1, quantidade_valida=1)
        .count()
    )
    if validos != total_lancamentos:
        raise RuntimeError(
            'Falha no backfill: nem todos os lançamentos possuem exatamente '
            'uma classificação idêntica ao Plano de Contas e valor legados.'
        )


def preservar_classificacoes_no_rollback(apps, schema_editor):
    # A reversão estrutural removerá a tabela; não há alteração nos lançamentos legados.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_obras_centros_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiroClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes_contabeis', to='financeiro.lancamentofinanceiro', verbose_name='Lançamento')),
                ('plano_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classificacoes_financeiras', to='financeiro.planoconta', verbose_name='Plano de contas')),
            ],
            options={
                'verbose_name': 'Classificação contábil do lançamento',
                'verbose_name_plural': 'Classificações contábeis dos lançamentos',
                'ordering': ['ordem', 'id'],
                'indexes': [models.Index(fields=['lancamento', 'ordem'], name='fin_class_lanc_ord_idx'), models.Index(fields=['plano_conta', 'lancamento'], name='fin_class_cont_lanc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', Decimal('0.00'))), name='classificacao_financeira_valor_positivo'), models.UniqueConstraint(fields=('lancamento', 'plano_conta'), name='unique_classificacao_conta_lancamento')],
            },
        ),
        migrations.RunPython(
            preencher_classificacoes_unicas,
            preservar_classificacoes_no_rollback,
        ),
    ]
