# Generated by Django 6.0.7 on 2026-08-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_lancamentofinanceiroclassificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamentofinanceiroclassificacao',
            options={'ordering': ['ordem', 'id'], 'permissions': [('view_classificacoes_multiplas', 'Pode visualizar classificações contábeis múltiplas'), ('change_classificacoes_multiplas', 'Pode editar classificações contábeis múltiplas')], 'verbose_name': 'Classificação contábil do lançamento', 'verbose_name_plural': 'Classificações contábeis dos lançamentos'},
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.planoconta', verbose_name='Plano de contas'),
        ),
    ]
