# Generated by Django 6.0.7 on 2026-08-19 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0002_alter_proposta_options_proposta_aprovada_em_and_more'),
        ('financeiro', '0009_obras_centros_custo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ABERTA', 'Aberta'), ('EM_COTACAO', 'Em cotação'), ('PARCIALMENTE_ATENDIDA', 'Parcialmente atendida'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=25)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compra_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compra', to='financeiro.empresa')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compra', to='financeiro.centrocusto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_solicitacao', '-id'],
                'permissions': [('cancelar_solicitacao', 'Pode cancelar solicitação de compra')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSolicitacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=25)),
                ('status_novo', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ABERTA', 'Aberta'), ('EM_COTACAO', 'Em cotação'), ('PARCIALMENTE_ATENDIDA', 'Parcialmente atendida'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], max_length=25)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='compras.solicitacaocompra')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidade', models.CharField(max_length=20)),
                ('data_necessaria', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('tipo_origem', models.CharField(choices=[('PREVISTO', 'Previsto'), ('SUBSTITUICAO', 'Substituição'), ('NAO_PREVISTO', 'Não previsto')], default='NAO_PREVISTO', max_length=20)),
                ('quantidade_prevista_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('custo_unitario_previsto_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('descricao_item_substituido', models.CharField(blank=True, max_length=250)),
                ('cancelado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano_conta_previsto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao_compra', to='financeiro.planoconta')),
                ('proposta_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao_compra', to='comercial.propostaitem')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.solicitacaocompra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
