# Generated by Django 6.0.7 on 2026-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocompraitem',
            name='descricao_prevista_snapshot',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='solicitacaocompraitem',
            name='unidade_prevista_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
