# Generated by Django 6.0.7 on 2026-08-19 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_solicitacaocompraitem_descricao_prevista_snapshot_and_more'),
        ('financeiro', '0009_obras_centros_custo'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_cotacao', models.DateField(default=django.utils.timezone.localdate)),
                ('validade', models.DateField(blank=True, null=True)),
                ('prazo_entrega', models.CharField(blank=True, max_length=150)),
                ('condicao_pagamento', models.TextField(blank=True)),
                ('tipo_frete', models.CharField(blank=True, max_length=50)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('desconto_global', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos_globais', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos_compoem_custo', models.BooleanField(default=True)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('disponibilidade', models.CharField(blank=True, max_length=150)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida'), ('INVALIDADA', 'Invalidada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_compras', to='pessoas.pessoa')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_fornecedor_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fornecedor__razao_social', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoFornecedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_ofertada', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidade', models.CharField(max_length=20)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('preco_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos_item', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prazo_item', models.CharField(blank=True, max_length=150)),
                ('disponivel', models.BooleanField(default=True)),
                ('marca_modelo', models.CharField(blank=True, max_length=150)),
                ('observacao', models.TextField(blank=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.cotacaofornecedor')),
            ],
            options={
                'ordering': ['processo_item', 'cotacao'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(default=django.utils.timezone.localdate)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_cotacao_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_cotacao', to='financeiro.empresa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_cotacao_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_abertura', '-id'],
                'permissions': [('realizar_cotacao', 'Pode registrar cotações de fornecedores'), ('selecionar_fornecedor', 'Pode selecionar fornecedor vencedor'), ('cancelar_cotacao', 'Pode cancelar processo de cotação')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoProcessoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='compras.processocotacao')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cotacaofornecedor',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_fornecedor', to='compras.processocotacao'),
        ),
        migrations.CreateModel(
            name='ProcessoCotacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_cotada', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidade', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('nao_comprar', models.BooleanField(default=False)),
                ('justificativa_nao_compra', models.TextField(blank=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.processocotacao')),
                ('solicitacao_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_processo_cotacao', to='compras.solicitacaocompraitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EscolhaCotacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolhido_em', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField(blank=True)),
                ('era_menor_preco', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('escolhido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escolhas_cotacao', to=settings.AUTH_USER_MODEL)),
                ('oferta_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escolhas', to='compras.cotacaofornecedoritem')),
                ('processo_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escolha', to='compras.processocotacaoitem')),
            ],
        ),
        migrations.AddField(
            model_name='cotacaofornecedoritem',
            name='processo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='compras.processocotacaoitem'),
        ),
        migrations.AddConstraint(
            model_name='cotacaofornecedor',
            constraint=models.UniqueConstraint(fields=('processo', 'fornecedor'), name='uq_fornecedor_por_processo_cotacao'),
        ),
        migrations.AddConstraint(
            model_name='processocotacaoitem',
            constraint=models.UniqueConstraint(fields=('processo', 'solicitacao_item'), name='uq_item_solicitacao_por_processo_cotacao'),
        ),
        migrations.AddConstraint(
            model_name='cotacaofornecedoritem',
            constraint=models.UniqueConstraint(fields=('cotacao', 'processo_item'), name='uq_oferta_item_por_fornecedor'),
        ),
    ]
