# Generated by Django 6.0.7 on 2026-08-19 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_proposta_options_proposta_aprovada_em_and_more'),
        ('compras', '0003_cotacaofornecedor_cotacaofornecedoritem_and_more'),
        ('financeiro', '0009_obras_centros_custo'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('COTACAO', 'Cotação'), ('DIRETA', 'Direta'), ('EMERGENCIAL', 'Emergencial')], max_length=15)),
                ('justificativa_origem', models.TextField(blank=True)),
                ('nome_vendedor_fornecedor_snapshot', models.CharField(blank=True, max_length=150)),
                ('telefone_vendedor_snapshot', models.CharField(blank=True, max_length=30)),
                ('email_vendedor_snapshot', models.EmailField(blank=True, max_length=254)),
                ('numero_pedido_versatile', models.CharField(max_length=80)),
                ('numero_pedido_fornecedor', models.CharField(blank=True, max_length=80)),
                ('data_pedido', models.DateField(default=django.utils.timezone.localdate)),
                ('condicao_pagamento', models.TextField()),
                ('prazo_entrega', models.CharField(max_length=150)),
                ('tipo_frete', models.CharField(blank=True, max_length=50)),
                ('transportadora_nome_snapshot', models.CharField(blank=True, max_length=200)),
                ('transportadora_documento_snapshot', models.CharField(blank=True, max_length=30)),
                ('transportadora_contato_snapshot', models.CharField(blank=True, max_length=100)),
                ('dados_bancarios', models.TextField(blank=True)),
                ('instrucoes_entrega', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('responsavel_nome_snapshot', models.CharField(blank=True, max_length=150)),
                ('responsavel_cargo_snapshot', models.CharField(blank=True, max_length=100)),
                ('assinatura_textual', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('ENVIADO_FORNECEDOR', 'Enviado ao fornecedor'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=25)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_aprovados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='financeiro.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_enviados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_fornecedor', to='pessoas.pessoa')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_transportadora', to='pessoas.pessoa')),
            ],
            options={
                'ordering': ['-data_pedido', '-id'],
                'permissions': [('criar_pedido', 'Pode criar pedido de compra'), ('aprovar_pedido', 'Pode aprovar pedido de compra'), ('rejeitar_pedido', 'Pode rejeitar pedido de compra'), ('cancelar_pedido', 'Pode cancelar pedido de compra'), ('enviar_pedido', 'Pode enviar pedido ao fornecedor'), ('view_custos_compra', 'Pode visualizar custos de compras')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=25)),
                ('status_novo', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('ENVIADO_FORNECEDOR', 'Enviado ao fornecedor'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], max_length=25)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='compras.pedidocompra')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta_codigo_snapshot', models.CharField(blank=True, max_length=80)),
                ('descricao_mercadoria', models.CharField(max_length=250)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidade', models.CharField(max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frete_alocado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('outras_despesas_alocadas', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('observacao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('escolha_cotacao_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_item', to='compras.escolhacotacaoitem')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra')),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='financeiro.planoconta')),
                ('proposta_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='comercial.propostaitem')),
                ('solicitacao_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='compras.solicitacaocompraitem')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemAlocacaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_origem', models.CharField(choices=[('PREVISTO', 'Previsto'), ('SUBSTITUICAO', 'Substituição'), ('NAO_PREVISTO', 'Não previsto')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_pedido_compra', to='financeiro.centrocusto')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='compras.pedidocompraitem')),
                ('proposta_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_pedido_compra', to='comercial.propostaitem')),
                ('solicitacao_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_pedido_compra', to='compras.solicitacaocompraitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_pedido_versatile'), name='uq_numero_pedido_compra_empresa'),
        ),
    ]
