# Generated by Django 6.0.7 on 2026-08-19 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_pedidocompra_historicopedidocompra_pedidocompraitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopedidocompra',
            name='status_novo',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('ENVIADO_FORNECEDOR', 'Enviado ao fornecedor'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('PARCIALMENTE_RECEBIDO', 'Parcialmente recebido'), ('RECEBIDO', 'Recebido')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('ENVIADO_FORNECEDOR', 'Enviado ao fornecedor'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('PARCIALMENTE_RECEBIDO', 'Parcialmente recebido'), ('RECEBIDO', 'Recebido')], default='RASCUNHO', max_length=25),
        ),
        migrations.CreateModel(
            name='RecebimentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(default=django.utils.timezone.localdate)),
                ('numero_documento', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=15)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_compra_cancelados', to=settings.AUTH_USER_MODEL)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_compra_confirmados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='compras.pedidocompra')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_compra_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_recebimento', '-id'],
                'permissions': [('registrar_recebimento', 'Pode registrar recebimento de compra'), ('cancelar_recebimento', 'Pode cancelar recebimento confirmado'), ('resolver_divergencia_recebimento', 'Pode resolver divergência de recebimento')],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quantidade_aceita', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quantidade_rejeitada', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('observacao', models.TextField(blank=True)),
                ('possui_divergencia', models.BooleanField(default=False)),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_recebimento', to='compras.pedidocompraitem')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.recebimentocompra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DivergenciaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('QUANTIDADE_MENOR', 'Quantidade menor'), ('QUANTIDADE_MAIOR', 'Quantidade maior'), ('MATERIAL_INCORRETO', 'Material incorreto'), ('DANIFICADO', 'Danificado'), ('PRECO_DIVERGENTE', 'Preço divergente'), ('OUTRO', 'Outro')], max_length=25)),
                ('descricao', models.TextField()),
                ('quantidade_afetada', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('solucao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_recebimento_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('recebimento_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias', to='compras.recebimentocompraitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recebimentocompraitem',
            constraint=models.UniqueConstraint(fields=('recebimento', 'pedido_item'), name='uq_item_por_recebimento_compra'),
        ),
    ]
