# Generated by Django 6.0.7 on 2026-08-19 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_historicopedidocompra_status_novo_and_more'),
        ('financeiro', '0009_obras_centros_custo'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTA_FISCAL', 'Nota Fiscal'), ('FATURA', 'Fatura'), ('BOLETO', 'Boleto/cobrança'), ('RECIBO', 'Recibo'), ('OUTRO', 'Outro')], max_length=20)),
                ('numero', models.CharField(max_length=100)),
                ('numero_normalizado', models.CharField(editable=False, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=50)),
                ('serie_normalizada', models.CharField(blank=True, editable=False, max_length=50)),
                ('chave_fiscal', models.CharField(blank=True, max_length=100)),
                ('data_emissao', models.DateField()),
                ('data_entrada', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('condicao_pagamento', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_CONFERENCIA', 'Em conferência'), ('CONFERIDO', 'Conferido'), ('DIVERGENTE', 'Divergente'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('enviado_conferencia_em', models.DateTimeField(blank=True, null=True)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra_cancelados', to=settings.AUTH_USER_MODEL)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra_conferidos', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra', to='financeiro.empresa')),
                ('enviado_conferencia_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra_enviados_conferencia', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra', to='pessoas.pessoa')),
            ],
            options={
                'ordering': ['-data_emissao', '-id'],
                'permissions': [('conferir_documento_compra', 'Pode conferir documento de compra'), ('resolver_divergencia_documento', 'Pode resolver divergência de documento'), ('cancelar_documento_compra', 'Pode cancelar documento de compra'), ('view_valores_documento_compra', 'Pode visualizar valores de documento de compra')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_snapshot', models.CharField(max_length=250)),
                ('quantidade_faturada', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidade', models.CharField(max_length=20)),
                ('valor_unitario_faturado', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frete_alocado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('observacao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.documentocompra')),
                ('pedido_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_documento_compra', to='compras.pedidocompraitem')),
                ('plano_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_documento_compra', to='financeiro.planoconta')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DivergenciaDocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('QUANTIDADE_MAIOR', 'Quantidade maior'), ('QUANTIDADE_MENOR', 'Quantidade menor'), ('PRECO', 'Preço divergente'), ('FRETE', 'Frete divergente'), ('DESCONTO', 'Desconto divergente'), ('IMPOSTO', 'Imposto divergente'), ('DOCUMENTO_DUPLICADO', 'Documento duplicado'), ('ITEM_SEM_VINCULO', 'Item sem pedido/recebimento'), ('OUTRO', 'Outro')], max_length=25)),
                ('descricao', models.TextField()),
                ('quantidade_afetada', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('valor_afetado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bloqueante', models.BooleanField(default=True)),
                ('automatica', models.BooleanField(default=False)),
                ('resolvida', models.BooleanField(default=False)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('solucao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_documento_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias', to='compras.documentocompra')),
                ('documento_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divergencias', to='compras.documentocompraitem')),
            ],
            options={
                'ordering': ['resolvida', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCompraItemRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_vinculada', models.DecimalField(decimal_places=4, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_recebimentos', to='compras.documentocompraitem')),
                ('recebimento_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_documentos', to='compras.recebimentocompraitem')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCompraPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_pedidos', to='compras.documentocompra')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_documentos', to='compras.pedidocompra')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentocompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'fornecedor', 'tipo', 'numero_normalizado', 'serie_normalizada'), name='uq_documento_compra_identificacao'),
        ),
        migrations.AddConstraint(
            model_name='documentocompra',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_fiscal', ''), _negated=True), fields=('chave_fiscal',), name='uq_documento_compra_chave_fiscal'),
        ),
        migrations.AddConstraint(
            model_name='documentocompraitemrecebimento',
            constraint=models.UniqueConstraint(fields=('documento_item', 'recebimento_item'), name='uq_documento_item_recebimento'),
        ),
        migrations.AddConstraint(
            model_name='documentocomprapedido',
            constraint=models.UniqueConstraint(fields=('documento', 'pedido'), name='uq_documento_compra_pedido'),
        ),
    ]
