# Generated by Django 6.0.7 on 2026-08-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_documentocompra_documentocompraitem_and_more'),
        ('financeiro', '0009_obras_centros_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompraParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='compras.documentocompra')),
                ('parcela_financeira', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcela_documento_compra', to='financeiro.parcelafinanceira')),
            ],
            options={
                'ordering': ['numero', 'vencimento'],
                'permissions': [('view_preview_financeiro_documento', 'Pode visualizar preview financeiro de documento')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero'), name='uq_parcela_documento_compra')],
            },
        ),
    ]
