# Generated by Django 6.0.7 on 2026-08-19 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_documentocompraparcela'),
        ('financeiro', '0011_alter_lancamentofinanceiroclassificacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentocompra',
            options={'ordering': ['-data_emissao', '-id'], 'permissions': [('conferir_documento_compra', 'Pode conferir documento de compra'), ('resolver_divergencia_documento', 'Pode resolver divergência de documento'), ('cancelar_documento_compra', 'Pode cancelar documento de compra'), ('view_valores_documento_compra', 'Pode visualizar valores de documento de compra'), ('integrar_documento_financeiro', 'Pode integrar documento ao Financeiro'), ('estornar_documento_financeiro', 'Pode estornar integração financeira')]},
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_CONFERENCIA', 'Em conferência'), ('CONFERIDO', 'Conferido'), ('DIVERGENTE', 'Divergente'), ('CANCELADO', 'Cancelado'), ('INTEGRADO_FINANCEIRO', 'Integrado ao Financeiro')], default='RASCUNHO', max_length=25),
        ),
        migrations.CreateModel(
            name='IntegracaoDocumentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTEGRADO', 'Integrado'), ('ESTORNADO', 'Estornado')], default='INTEGRADO', max_length=15)),
                ('chave_idempotencia', models.CharField(max_length=100, unique=True)),
                ('integrado_em', models.DateTimeField(auto_now_add=True)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='integracao_financeira', to='compras.documentocompra')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos_documento_financeiro', to=settings.AUTH_USER_MODEL)),
                ('integrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integracoes_documento_financeiro', to=settings.AUTH_USER_MODEL)),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='integracao_documento_compra', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Integração de documento de compra com Financeiro',
                'verbose_name_plural': 'Integrações de documentos de compra com Financeiro',
                'ordering': ['-integrado_em', '-id'],
            },
        ),
    ]
